### ISSUE TITLE
Remove potential log noise

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#203] opened 2020-09-22 12:11 UTC
This is an excerpt from oxauth.log

```
19:44,570 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
19:59,582 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
20:14,566 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
20:29,562 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
20:44,567 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
20:59,566 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
21:14,568 INFO  [ForkJoinPool.commonPool-worker-3] [org.gluu.service.logger.LoggerService] (LoggerService.java:165) - Updated log level of '120' loggers to INFO
```

> We got this after logging libs update
> Our code check if log level need to be updated for specifc logger
> And it should not set log level if it’s set right already
> But… there is something wrong and we need to update this to works well with latest libs

**Comment by yuriyz** [comment] 2020-09-24 11:52
Duplicate of https://github.com/GluuFederation/oxCore/issues/203

**Closed by yuriyz** 2020-09-24 11:52 UTC
Labels: enhancement

**Comment by jgomer2001** [comment] 2020-09-25 12:01
> Duplicate of #203

@yuriyz it will always be duplicate of itself :D :D :D

**Comment by yuriyz** [comment] 2020-09-25 12:06
Always true :D . Correct link https://github.com/GluuFederation/oxCore/issues/204
